### ISSUE TITLE
Issue: Exception-page when linux user logs out

### ISSUE THREAD

**Issue by AriinPHD** [moebooru/moebooru#98]
Getting this error when logging out from the SSH session to the remote server (full log linked at bottom):
![booru_error_2018-03-12_16-23-32](https://user-images.githubusercontent.com/5846389/37292732-d3bfa6ea-2611-11e8-8402-155f02b11b0f.png)

As soon as I log back in, the site start working again.

I'm running it in a screen because I can't do anything when the server is just a live-streamed-log.... thing..... Not sure how to run this stuff as a service. I don't need to resume the screen for the site to start working; I just need to be logged in (which I can't be 24/7).

Full error:
https://pastebin.com/ujbvAVnc

**Comment by euank** [comment]
This seems more likely to be an environment error than anything else; it sounds like the server may be configured to have `/home/$USER` be an nfs mount or some other transient mount which vanishes when you log out.

Are you running this on a normally configured server (e.g. an ec2 instance)? What distro?

> I'm running it in a screen because I can't do anything when the server is just a live-streamed-log.... thing..... Not sure how to run this stuff as a service

The typical way to do that is to use some process management system to run it, such as systemd, though tools like docker, monit, etc, can fill that role to some degree. A systemd service file is probably the right answer if you're not sure.

**Comment by AriinPHD** [comment]
Thanks for the reply @euank !

It's a regular Ubuntu server installation on an old laptop. Nothing fancy, nothing "cloud". Just an old lenovo that I'm trying to set this up on to learn how it works before I put it up on a server. I'm aiming for an offline/a local booru for archiving purposes.

I haven't experienced this issue before, so I'm sort of at a loss - sadly - and I wasn't able to find an answer by myself. Also I have not used these tools that you use for installing this stuff (bundle) so perhaps I've done something wrong.

The guide (what little exists) leads me to think this setup is for experienced linux users only. That's fair. I'd just waste your time; so i'd appreciate knowing if that was the case. :)

Thanks again!

**Comment by euank** [comment]
Weird, the ENOENT error seems odd for that. It could be worth trying `loginctl enable-linger $USER` in case the session vanishing matters, assuming this is a recent systemd-enabled ubuntu. If that were the problem I'd just expect the process to die, but who knows.

You could also try sshing in as a different user and looking around to see if there are earlier errors in the booru's logs. Actually, checking those logs vs just the error on the web page could be helpful since there may be earlier relevant errors.

> Also I have not used these tools that you use for installing this stuff

The tools I mentioned, namely systemd, are for running things, not installing them. Running it as such a service would be preferable since it could start on boot, have better security configuration (e.g. be tied to a booru user which is not your login user), collect and rotate logs more easily, etc.
You're right that you shouldn't expect support for that here though. Other pages do document that sort of stuff well though.

**Comment by nanaya** [comment]
Many years late but create a global systemctl unit or use supervisor or something.
